apiVersion: v1
kind: Namespace
metadata:
  name: config-backend

---
apiVersion: v1
data:
  DBNAME: "produk"
  DBPASSWORD: "michan123"
  DBPORT: "5432"
  DBHOST: "100.69.186.192"
  DBUSER: "michan"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

kind: ConfigMap
metadata:
  name: service-backend
  namespace: config-backend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: config-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: POSShop
      tier: backend
  template:
    metadata:
      labels:
        app: POSShop
        tier: backend
    spec:
      containers:
        - name: backend
          image: michan11/backend-api:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: service-backend
          livenessProbe:
            httpGet:
              path: /product
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: config-backend
spec:
  selector:
    app: POSShop
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: backendport
